USE [MASTER]

CREATE LOGIN [LOGIN_NAME] WITH PASSWORD=N'PASSWORD'
GO

CREATE USER [USER_NAME] FOR LOGIN [LOGIN_NAME] WITH DEFAULT_SCHEMA=dbo
GO

--------------------------------------------------
USE [USER_DB]

CREATE USER [USER_NAME] FOR LOGIN [LOGIN_NAME] WITH DEFAULT_SCHEMA=dbo
GO

EXEC SP_ADDROLEMEMBER 'DB_DATAREADER', 'USER_NAME';
EXEC SP_DROPROLEMEMBER 'DB_DATAREADER', 'USER_NAME';
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: [SCHEMA_NAME] TO [USER_NAME];
DENY INSERT, UPDATE, DELETE ON SCHEMA :: [SCHEMA_NAME] TO [USER_NAME];

GRANT CREATE PROCEDURE TO [USER_NAME]
GRANT EXECUTE ON SCHEMA :: [SCHEMA_NAME] TO [USER_NAME]

---------------------------------------------------
CREATE USER [USER_NAME] FROM EXTERNAL PROVIDER WITH DEFAULT_SCHEMA=[dbo]
GO
EXEC sp_addrolemember N'db_datareader', N'USER_NAME'
GO

---------------------------------------------------
GRANT VIEW DEFINITION ON SCHEMA :: SEMANTIC TO [USER_NAME]